AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  schedule-reminder

  Notion-based schedule reminder service that sends notifications via Discord/LINE/Slack

Globals:
  Function:
    Timeout: 60
    MemorySize: 256

Resources:
  ScheduleReminderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: .
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 9 * * ? *)  # Run daily at 00:00 UTC (09:00 JST)
            Description: Daily reminder check
            Enabled: true
      Policies:
        - Statement:
          - Sid: SSMParameterAccess
            Effect: Allow
            Action:
              - ssm:GetParameter
              - ssm:GetParameters
            Resource:
              - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/lambda-functions/schedule-reminder/*'
    Metadata:
      BuildMethod: go1.x

Outputs:
  ScheduleReminderFunction:
    Description: "Schedule Reminder Lambda Function ARN"
    Value: !GetAtt ScheduleReminderFunction.Arn

  ScheduleReminderFunctionIamRole:
    Description: "IAM Role for Schedule Reminder function"
    Value: !GetAtt ScheduleReminderFunctionRole.Arn
