AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  schedule-reminder

  Notion-based schedule reminder service that sends notifications via Discord/LINE/Slack

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - local
      - prod
    Description: Environment name
  AwsEndpointUrl:
    Type: String
    Default: ""
    Description: AWS Endpoint (local environment only)
  ParamPathPrefix:
    Type: String
    Default: "/lambda-functions/schedule-reminder"
    Description: Parameter store path prefix

Conditions:
  IsLocalDeployment: !Equals [!Ref Environment, local]

Globals:
  Function:
    Timeout: 60
    MemorySize: 256

Resources:
  ScheduleReminderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: .
      Runtime: provided.al2023
      Architectures:
        - x86_64
      Environment:
        Variables:
          AWS_ENDPOINT_URL: !If [IsLocalDeployment, !Ref AwsEndpointUrl, !Ref "AWS::NoValue"]
          SSM_PARAM_PREFIX: !If [IsLocalDeployment, !Ref ParamPathPrefix, !Ref "AWS::NoValue"]
      Events:
        DailySchedule:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: cron(0 9 * * ? *)
            ScheduleExpressionTimezone: Asia/Tokyo
      Policies:
        - Statement:
          - Sid: SSMParameterAccess
            Effect: Allow
            Action:
              - ssm:GetParameter
              - ssm:GetParameters
            Resource:
              - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/lambda-functions/schedule-reminder/*'
    Metadata:
      BuildMethod: go1.x

Outputs:
  ScheduleReminderFunction:
    Description: "Schedule Reminder Lambda Function ARN"
    Value: !GetAtt ScheduleReminderFunction.Arn

  ScheduleReminderFunctionIamRole:
    Description: "IAM Role for Schedule Reminder function"
    Value: !GetAtt ScheduleReminderFunctionRole.Arn
